In [9]:
# Face Recognition

# Importing the libraries
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image
model = load_model('facefeatures_new_model.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][1]>0.5):
            name='Jashan'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

<>:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\jasha\AppData\Local\Temp/ipykernel_23076/2164842435.py:27: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


[[1.0000000e+00 4.2383398e-23]]
[[9.993711e-01 6.289294e-04]]
[[8.726519e-15 1.000000e+00]]
[[0.7219921  0.27800786]]
[[7.2806987e-09 1.0000000e+00]]
[[5.7221987e-06 9.9999428e-01]]
[[6.7358045e-04 9.9932647e-01]]
[[0.9158239  0.08417608]]
[[0.61445636 0.38554364]]
[[9.9981183e-01 1.8823413e-04]]
[[0.00862408 0.991376  ]]
[[1.0000000e+00 2.0643788e-10]]
[[4.2477481e-05 9.9995756e-01]]
[[4.932500e-07 9.999995e-01]]
[[0.9123441  0.08765593]]
[[1.000000e+00 5.429118e-29]]
[[1.000000e+00 7.764121e-18]]
[[9.9999952e-01 4.6331775e-07]]
[[1.000000e+00 7.079049e-12]]
[[0.9967416  0.00325846]]
[[0.93363076 0.06636923]]
[[1.00000000e+00 1.00924364e-11]]
[[1.0000000e+00 8.5205916e-24]]
[[1.0000000e+00 2.7700016e-16]]
[[1.0000000e+00 1.8631878e-09]]
[[1.000000e+00 8.250438e-14]]
[[9.9999535e-01 4.6538944e-06]]
[[8.651689e-12 1.000000e+00]]
[[1.0000000e+00 1.4783925e-18]]
[[9.783109e-06 9.999902e-01]]
[[1.0000000e+00 1.6056878e-16]]
[[1.000000e+00 4.973455e-22]]
[[1.000000e+00 5.839917e-16]]
[[9.99